import Foundation
import SwiftData
import SwiftUI

enum AppScreen {
    case welcome
    case profile
    case main
    case checkInEntry
    case manualCheckIn
    case aiCheckIn
    case completion
    case activityInsight
}

enum AppTab: String, CaseIterable {
    case cloudy = "Cloudy"
    case log = "Log"
    case home = "Home"
    case progress = "Progress"
    case profile = "Profile"

    var icon: String {
        switch self {
        case .cloudy: "cloud"
        case .log: "plus.circle"
        case .home: "house"
        case .progress: "chart.bar"
        case .profile: "person.circle"
        }
    }
}

enum RiskPredictionMode {
    case localFallback
    case loadingRemote
    case remoteModel
    case unavailable(String)

    var label: String {
        switch self {
        case .localFallback:
            return "Local rules estimate"
        case .loadingRemote:
            return "Updating model estimate..."
        case .remoteModel:
            return "LightGBM model estimate"
        case .unavailable:
            return "Local fallback estimate"
        }
    }

    var detail: String? {
        switch self {
        case .localFallback:
            return "Start the backend API to use the trained model."
        case .loadingRemote:
            return nil
        case .remoteModel:
            return "Generated by the backend reduced 18-feature LightGBM model."
        case .unavailable(let message):
            return message
        }
    }
}

@MainActor
final class AppStore: ObservableObject {
    @Published var screen: AppScreen = .welcome
    @Published var selectedTab: AppTab = .home
    @Published var profile = MockData.profile
    @Published var checkIn = MockData.checkIn
    @Published var weeklyRisk = MockData.weeklyRisk
    @Published var dailyInsights = MockData.dailyInsights
    @Published var riskPredictionMode: RiskPredictionMode = .localFallback
    @Published var authEmail = ""
    @Published var authPassword = ""
    @Published var accountEmail = ""
    @Published var authMessage = ""
    @Published var cloudSyncMessage = ""
    @Published var isAuthenticating = false
    @Published var isCloudSyncing = false
    @Published var hasAcceptedPrivacyTerms = false
    private var hasLoadedPersistedData = false
    private let riskPredictionAPI = RiskPredictionAPI()
    private let accountAPI = AccountAPI()
    private var authToken: String?

    var isSignedIn: Bool {
        authToken != nil
    }

    init() {
        authToken = KeychainStore.read(account: "authToken")
        accountEmail = UserDefaults.standard.string(forKey: "accountEmail") ?? ""
        authEmail = accountEmail
        hasAcceptedPrivacyTerms = UserDefaults.standard.bool(forKey: "hasAcceptedPrivacyTerms")
        refreshLocalRiskAndInsights()
        if authToken != nil {
            cloudSyncMessage = "Signed in as \(accountEmail)"
        }
    }

    func showMain(tab: AppTab = .home) {
        selectedTab = tab
        screen = .main
    }

    func startCheckIn() {
        selectedTab = .log
        screen = .checkInEntry
    }

    func completeCheckIn() {
        checkIn.isCompleted = true
        refreshLocalRiskAndInsights()
        refreshRemoteRiskPredictionIfPossible()
        screen = .completion
    }

    func loadPersistedDataIfNeeded(profile: StoredUserProfile?, checkIn: StoredDailyCheckIn?) {
        guard !hasLoadedPersistedData else { return }
        if let profile {
            self.profile = profile.userProfile
        }
        if let checkIn {
            self.checkIn = checkIn.dailyCheckIn
        }
        refreshLocalRiskAndInsights()
        refreshRemoteRiskPredictionIfPossible()
        hasLoadedPersistedData = true
    }

    func loadPersistedDataIfNeeded(from context: ModelContext) {
        guard !hasLoadedPersistedData else { return }
        let profileDescriptor = FetchDescriptor<StoredUserProfile>(
            sortBy: [SortDescriptor(\.updatedAt, order: .reverse)]
        )
        let checkInDescriptor = FetchDescriptor<StoredDailyCheckIn>(
            sortBy: [SortDescriptor(\.updatedAt, order: .reverse)]
        )
        let profile = try? context.fetch(profileDescriptor).first
        let checkIn = try? context.fetch(checkInDescriptor).first
        loadPersistedDataIfNeeded(profile: profile, checkIn: checkIn)
    }

    func saveProfile(in context: ModelContext) {
        let missingItems = profileMissingDataItems()
        let descriptor = FetchDescriptor<StoredUserProfile>(
            sortBy: [SortDescriptor(\.updatedAt, order: .reverse)]
        )
        if let existing = try? context.fetch(descriptor).first {
            existing.update(from: profile, missingItems: missingItems)
        } else {
            context.insert(StoredUserProfile(profile: profile, missingItems: missingItems))
        }
        try? context.save()
        refreshLocalRiskAndInsights()
        refreshRemoteRiskPredictionIfPossible()
        syncProfileToCloud()
    }

    func saveCheckIn(in context: ModelContext) {
        let missingItems = checkInMissingDataItems()
        let startOfToday = Calendar.current.startOfDay(for: Date())
        let descriptor = FetchDescriptor<StoredDailyCheckIn>(
            sortBy: [SortDescriptor(\.updatedAt, order: .reverse)]
        )
        let existing = (try? context.fetch(descriptor))?
            .first { Calendar.current.isDate($0.checkInDate, inSameDayAs: startOfToday) }
        if let existing {
            existing.update(from: checkIn, missingItems: missingItems)
        } else {
            context.insert(StoredDailyCheckIn(checkIn: checkIn, missingItems: missingItems))
        }
        try? context.save()
        refreshLocalRiskAndInsights()
        refreshRemoteRiskPredictionIfPossible()
    }

    func refreshLocalRiskAndInsights() {
        let result = LocalRiskEngine.evaluate(profile: profile, checkIn: checkIn)
        weeklyRisk = result.risk
        dailyInsights = result.insights
    }

    var currentModelInputPayload: ModelInputPayload {
        ModelInputMapper.makePayload(profile: profile, checkIn: checkIn)
    }

    func refreshRemoteRiskPredictionIfPossible() {
        let payload = currentModelInputPayload
        if !payload.missingRequiredInputs.isEmpty {
            riskPredictionMode = .unavailable("Complete required model inputs to use the trained prediction model.")
            syncCheckInToCloud()
            return
        }

        riskPredictionMode = .loadingRemote
        Task {
            do {
                let response = try await riskPredictionAPI.predict(payload: payload)
                applyRemoteRiskPrediction(response)
                syncCheckInToCloud(riskResult: response)
            } catch {
                riskPredictionMode = .unavailable(error.localizedDescription)
                syncCheckInToCloud()
            }
        }
    }

    func logIn() {
        authenticate(isRegistering: false)
    }

    func createAccount() {
        authenticate(isRegistering: true)
    }

    func acceptPrivacyTerms() {
        hasAcceptedPrivacyTerms = true
        UserDefaults.standard.set(true, forKey: "hasAcceptedPrivacyTerms")
    }

    func signOut() {
        authToken = nil
        accountEmail = ""
        authPassword = ""
        authMessage = "Signed out."
        cloudSyncMessage = ""
        KeychainStore.delete(account: "authToken")
        UserDefaults.standard.removeObject(forKey: "accountEmail")
    }

    func deleteAccount() {
        guard let authToken else {
            signOut()
            return
        }
        cloudSyncMessage = "Deleting account..."
        Task {
            do {
                try await accountAPI.deleteAccount(token: authToken)
                signOut()
                cloudSyncMessage = "Account deleted."
                screen = .welcome
            } catch {
                cloudSyncMessage = "Account deletion failed: \(error.localizedDescription)"
            }
        }
    }

    func exportAccountData() {
        guard let authToken else {
            cloudSyncMessage = "Sign in to export cloud data."
            return
        }
        cloudSyncMessage = "Exporting account data..."
        Task {
            do {
                let data = try await accountAPI.exportAccountData(token: authToken)
                let kilobytes = max(1, data.count / 1024)
                cloudSyncMessage = "Data export ready (\(kilobytes) KB JSON)."
            } catch {
                cloudSyncMessage = "Data export failed: \(error.localizedDescription)"
            }
        }
    }

    private func authenticate(isRegistering: Bool) {
        guard hasAcceptedPrivacyTerms else {
            authMessage = "Review and accept Privacy & Safety before continuing."
            return
        }
        guard !authEmail.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            authMessage = "Enter your email."
            return
        }
        guard authPassword.count >= 8 else {
            authMessage = "Password must be at least 8 characters."
            return
        }

        isAuthenticating = true
        authMessage = isRegistering ? "Creating account..." : "Signing in..."
        Task {
            do {
                let response: AuthResponse
                if isRegistering {
                    response = try await accountAPI.register(
                        email: authEmail,
                        password: authPassword,
                        name: profile.name
                    )
                } else {
                    response = try await accountAPI.login(
                        email: authEmail,
                        password: authPassword
                    )
                }

                authToken = response.token
                accountEmail = response.user.email
                KeychainStore.save(response.token, account: "authToken")
                UserDefaults.standard.set(response.user.email, forKey: "accountEmail")
                authMessage = isRegistering ? "Account created." : "Signed in."
                cloudSyncMessage = "Signed in as \(response.user.email)"
                isAuthenticating = false

                if isRegistering {
                    syncProfileToCloud()
                    screen = .profile
                } else {
                    await loadCloudData()
                    showMain(tab: .home)
                }
            } catch {
                isAuthenticating = false
                authMessage = error.localizedDescription
            }
        }
    }

    private func loadCloudData() async {
        guard let authToken else { return }
        isCloudSyncing = true
        do {
            if let cloudProfile = try await accountAPI.fetchProfile(token: authToken) {
                profile = cloudProfile
            }
            if let cloudCheckIn = try await accountAPI.fetchLatestCheckIn(token: authToken) {
                checkIn = cloudCheckIn
            }
            refreshLocalRiskAndInsights()
            refreshRemoteRiskPredictionIfPossible()
            cloudSyncMessage = "Cloud data loaded."
        } catch {
            cloudSyncMessage = "Could not load cloud data: \(error.localizedDescription)"
        }
        isCloudSyncing = false
    }

    private func syncProfileToCloud() {
        guard let authToken else { return }
        isCloudSyncing = true
        Task {
            do {
                try await accountAPI.saveProfile(profile, token: authToken)
                cloudSyncMessage = "Profile synced to cloud."
            } catch {
                cloudSyncMessage = "Profile sync failed: \(error.localizedDescription)"
            }
            isCloudSyncing = false
        }
    }

    private func syncCheckInToCloud(riskResult: RiskPredictionResponse? = nil) {
        guard let authToken else { return }
        let payload = currentModelInputPayload
        isCloudSyncing = true
        Task {
            do {
                try await accountAPI.saveCheckIn(
                    checkIn,
                    token: authToken,
                    modelPayload: payload,
                    riskResult: riskResult
                )
                cloudSyncMessage = "Check-in synced to cloud."
            } catch {
                cloudSyncMessage = "Check-in sync failed: \(error.localizedDescription)"
            }
            isCloudSyncing = false
        }
    }

    private func applyRemoteRiskPrediction(_ response: RiskPredictionResponse) {
        weeklyRisk = WeeklyRisk(
            score: response.percent,
            band: response.band,
            increasing: response.increasingFactors,
            decreasing: response.decreasingFactors
        )
        if !response.suggestions.isEmpty {
            dailyInsights = response.suggestions.map { suggestion in
                DailyInsight(
                    icon: iconName(for: suggestion.domain),
                    title: suggestion.title,
                    detail: suggestion.text
                )
            }
        }
        riskPredictionMode = .remoteModel
    }

    func profileMissingDataItems() -> [MissingDataItem] {
        var items: [MissingDataItem] = []
        addRequiredString(&items, field: "age", label: "Age", value: profile.age)
        addRequiredChoice(&items, field: "sex_at_birth", label: "Sex assigned at birth", value: profile.sexAtBirth)
        if profile.sexAtBirth == "Female" {
            addRequiredChoice(&items, field: "pregnancy_history", label: "Pregnancy history", value: profile.hasBeenPregnant)
            if profile.hasBeenPregnant == "Yes" {
                addRequiredChoice(&items, field: "gestational_diabetes", label: "Gestational diabetes history", value: profile.gestationalDiabetes)
            }
        }
        if profile.raceEthnicity.isEmpty {
            items.append(MissingDataItem(field: "race_ethnicity", label: "Race and ethnicity", code: MissingDataCode.missing))
        } else if profile.raceEthnicity.contains("Prefer not to answer") {
            items.append(MissingDataItem(field: "race_ethnicity", label: "Race and ethnicity", code: MissingDataCode.preferNotToAnswer))
        }
        addRequiredString(&items, field: "height_feet", label: "Height feet", value: profile.heightFeet)
        addRequiredString(&items, field: "height_inches", label: "Height inches", value: profile.heightInches)
        addRequiredChoice(&items, field: "family_history_diabetes", label: "Family history of diabetes", value: profile.familyHistoryDiabetes)
        addRequiredChoice(&items, field: "hypertension_history", label: "Hypertension history", value: profile.hypertensionHistory)
        if profile.hypertensionHistory == "Yes" {
            addRequiredChoice(&items, field: "antihypertensive_medication", label: "High blood pressure medication", value: profile.antihypertensiveMedication)
        }
        addRequiredChoice(&items, field: "high_cholesterol", label: "High cholesterol", value: profile.highCholesterol)
        addRequiredChoice(&items, field: "smoking_status", label: "Smoking status", value: profile.smokingStatus)
        addRequiredChoice(&items, field: "alcohol_frequency", label: "Alcohol frequency", value: profile.alcoholFrequency)
        return items
    }

    func checkInMissingDataItems() -> [MissingDataItem] {
        var items: [MissingDataItem] = []
        addRequiredString(&items, field: "weight", label: "Weight", value: checkIn.weight)
        addRequiredString(&items, field: "waist_circumference", label: "Waist circumference", value: checkIn.waist)
        if !checkIn.hasRecentBloodPressure {
            items.append(MissingDataItem(field: "blood_pressure", label: "Blood pressure", code: MissingDataCode.noRecentReading))
        } else {
            addRequiredString(&items, field: "systolic_bp", label: "Systolic blood pressure", value: checkIn.systolic)
            addRequiredString(&items, field: "diastolic_bp", label: "Diastolic blood pressure", value: checkIn.diastolic)
            addRequiredString(&items, field: "blood_pressure_date", label: "Blood pressure date measured", value: checkIn.bloodPressureDate)
        }
        addRequiredString(&items, field: "sleep_hours", label: "Sleep duration", value: checkIn.sleepHours)
        if checkIn.activeToday == nil {
            items.append(MissingDataItem(field: "physical_activity_today", label: "Physical activity", code: MissingDataCode.missing))
        } else if checkIn.activeToday == true {
            addRequiredString(&items, field: "activity_type", label: "Activity type", value: checkIn.activityType)
            addRequiredString(&items, field: "activity_duration", label: "Activity duration", value: checkIn.activityDuration)
        }
        addRequiredChoice(&items, field: "movement_breaks", label: "Movement breaks", value: checkIn.movementBreaks)
        return items
    }

    private func addRequiredString(_ items: inout [MissingDataItem], field: String, label: String, value: String) {
        if value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            items.append(MissingDataItem(field: field, label: label, code: MissingDataCode.missing))
        }
    }

    private func addRequiredChoice(_ items: inout [MissingDataItem], field: String, label: String, value: String) {
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty {
            items.append(MissingDataItem(field: field, label: label, code: MissingDataCode.missing))
        } else if trimmed == "Prefer not to answer" {
            items.append(MissingDataItem(field: field, label: label, code: MissingDataCode.preferNotToAnswer))
        } else if trimmed == "Not sure" {
            items.append(MissingDataItem(field: field, label: label, code: MissingDataCode.notSure))
        }
    }

    func applyHealthImport(_ result: HealthImportResult) {
        if let weightPounds = result.weightPounds {
            checkIn.weight = String(format: "%.0f", weightPounds)
            checkIn.weightUnit = "lb"
        }
        if let systolic = result.systolic, let diastolic = result.diastolic {
            checkIn.systolic = String(format: "%.0f", systolic)
            checkIn.diastolic = String(format: "%.0f", diastolic)
            checkIn.bloodPressureDate = "Today"
            checkIn.hasRecentBloodPressure = true
        }
        if let sleepHours = result.sleepHours {
            checkIn.sleepHours = String(format: "%.1f", sleepHours)
        }
        if let activityMinutes = result.activityMinutes, activityMinutes > 0 {
            checkIn.activeToday = true
            checkIn.activityType = result.activityName ?? "Workout"
            checkIn.activityDuration = "\(activityMinutes)"
        }
        refreshLocalRiskAndInsights()
        refreshRemoteRiskPredictionIfPossible()
    }

    private func iconName(for domain: String) -> String {
        switch domain {
        case "sleep":
            return "moon.zzz"
        case "movement":
            return "figure.stand"
        case "diet":
            return "fork.knife"
        case "alcohol":
            return "wineglass"
        case "maintenance":
            return "checkmark.circle"
        default:
            return "sparkles"
        }
    }
}

struct UserProfile: Codable {
    var name: String
    var age: String
    var sexAtBirth: String
    var hasBeenPregnant: String
    var gestationalDiabetes: String
    var raceEthnicity: [String]
    var heightFeet: String
    var heightInches: String
    var familyHistoryDiabetes: String
    var hypertensionHistory: String
    var antihypertensiveMedication: String
    var highCholesterol: String
    var smokingStatus: String
    var alcoholFrequency: String
}

struct DailyCheckIn: Codable {
    var weight: String
    var weightUnit: String
    var waist: String
    var waistUnit: String
    var systolic: String
    var diastolic: String
    var bloodPressureDate: String
    var hasRecentBloodPressure: Bool
    var sleepHours: String
    var activeToday: Bool?
    var activityType: String
    var activityDuration: String
    var movementBreaks: String
    var foodJournal: String
    var dailyReflection: String
    var isCompleted: Bool
}

struct WeeklyRisk: Codable {
    var score: Int
    var band: String
    var increasing: [String]
    var decreasing: [String]
}

enum MockData {
    static let profile = UserProfile(
        name: "Chenyi",
        age: "34",
        sexAtBirth: "Female",
        hasBeenPregnant: "Yes",
        gestationalDiabetes: "No",
        raceEthnicity: ["Non-Hispanic Asian"],
        heightFeet: "5",
        heightInches: "6",
        familyHistoryDiabetes: "Yes",
        hypertensionHistory: "No",
        antihypertensiveMedication: "No",
        highCholesterol: "No",
        smokingStatus: "Never smoked",
        alcoholFrequency: "Never in the past 12 months"
    )

    static let checkIn = DailyCheckIn(
        weight: "148",
        weightUnit: "lb",
        waist: "33",
        waistUnit: "in",
        systolic: "122",
        diastolic: "78",
        bloodPressureDate: "Today",
        hasRecentBloodPressure: true,
        sleepHours: "6",
        activeToday: true,
        activityType: "Brisk walking",
        activityDuration: "18",
        movementBreaks: "A few times during the day",
        foodJournal: "Added",
        dailyReflection: "",
        isCompleted: false
    )

    static let weeklyRisk = WeeklyRisk(
        score: 64,
        band: "High Risk",
        increasing: ["Waist circumference", "BMI", "High blood pressure history"],
        decreasing: ["Younger age", "Typical sleep duration"]
    )

    static let dailyInsights = [
        DailyInsight(
            icon: "figure.walk",
            title: "Physical activity",
            detail: "A 10-minute walk after your next meal could add a little more movement."
        ),
        DailyInsight(
            icon: "figure.stand",
            title: "Movement breaks",
            detail: "Try standing or walking for 2-3 minutes during your next hour of sitting."
        ),
        DailyInsight(
            icon: "fork.knife",
            title: "Food journal",
            detail: "Review today's meals and notice anything that stood out."
        )
    ]
}
