import Foundation
import SwiftData
import SwiftUI

enum AppScreen {
    case welcome
    case profile
    case main
    case checkInEntry
    case manualCheckIn
    case aiCheckIn
    case completion
    case activityInsight
}

enum AppTab: String, CaseIterable {
    case log = "Log"
    case home = "Home"
    case progress = "Progress"
    case profile = "Profile"

    var icon: String {
        switch self {
        case .log: "plus.circle"
        case .home: "house"
        case .progress: "chart.bar"
        case .profile: "person.circle"
        }
    }
}

enum RiskPredictionMode {
    case localFallback
    case loadingRemote
    case remoteModel
    case unavailable(String)

    var label: String {
        switch self {
        case .localFallback:
            return "Local rules estimate"
        case .loadingRemote:
            return "Updating model estimate..."
        case .remoteModel:
            return "LightGBM model estimate"
        case .unavailable:
            return "Local fallback estimate"
        }
    }

    var detail: String? {
        switch self {
        case .localFallback:
            return "Start the backend API to use the trained model."
        case .loadingRemote:
            return nil
        case .remoteModel:
            return "Generated by the backend reduced 18-feature LightGBM model."
        case .unavailable(let message):
            return message
        }
    }
}

@MainActor
final class AppStore: ObservableObject {
    @Published var screen: AppScreen = .welcome
    @Published var selectedTab: AppTab = .home
    @Published var profile = MockData.profile
    @Published var checkIn = MockData.checkIn
    @Published var weeklyRisk = MockData.weeklyRisk
    @Published var dailyInsights = MockData.dailyInsights
    @Published var riskPredictionMode: RiskPredictionMode = .localFallback
    @Published var authEmail = ""
    @Published var authPassword = ""
    @Published var accountEmail = ""
    @Published var authMessage = ""
    @Published var cloudSyncMessage = ""
    @Published var isAuthenticating = false
    @Published var isCloudSyncing = false
    @Published var isEstimatingNutrition = false
    @Published var nutritionEstimateMessage = ""
    @Published var dailyInsightsSource = "Local rules"
    @Published var selectedDailyInsightTitle = "Physical activity"
    @Published var hasAcceptedPrivacyTerms = false
    @Published var checkInSource = "manual_entry"
    @Published var checkInProvenance: [String: String] = [:]
    private var hasLoadedPersistedData = false
    private let riskPredictionAPI = RiskPredictionAPI()
    private let nutritionEstimateAPI = NutritionEstimateAPI()
    private let dailyInsightsAPI = DailyInsightsAPI()
    private let accountAPI = AccountAPI()
    private var authToken: String?
    private let weeklyCheckInWeekday = 4

    var isSignedIn: Bool {
        authToken != nil
    }

    var shouldShowWeeklyCheckIn: Bool {
        Self.isWeeklyCheckInDay(Date(), weekday: weeklyCheckInWeekday)
    }

    var canGenerateDailyFeedback: Bool {
        profileMissingDataItems().isEmpty && checkInMissingDataItems().isEmpty
    }

    var featureFlags: [String: Int] {
        var flags: [String: Int] = [:]
        for (field, value) in profile.featureFlags {
            flags["profile.\(field)"] = value
        }
        for (field, value) in checkIn.featureFlags {
            flags["check_in.\(field)"] = value
        }
        return flags
    }

    init() {
        authToken = KeychainStore.read(account: "authToken")
        accountEmail = UserDefaults.standard.string(forKey: "accountEmail") ?? ""
        authEmail = accountEmail
        hasAcceptedPrivacyTerms = UserDefaults.standard.bool(forKey: "hasAcceptedPrivacyTerms")
        refreshLocalRiskAndInsights()
        if authToken != nil {
            cloudSyncMessage = "Signed in as \(accountEmail)"
        }
    }

    func showMain(tab: AppTab = .home) {
        selectedTab = tab
        screen = .main
    }

    func startCheckIn() {
        selectedTab = .log
        screen = .checkInEntry
    }

    func completeCheckIn() {
        guard canGenerateDailyFeedback else {
            markFeedbackWaitingForRequiredAnswers()
            return
        }
        checkIn.isCompleted = true
        refreshFeedbackIfReady()
        screen = .completion
    }

    func loadPersistedDataIfNeeded(profile: StoredUserProfile?) {
        guard !hasLoadedPersistedData else { return }
        if let profile {
            self.profile = profile.userProfile
        }
        resetDailyCheckInForNewSession()
        normalizeFoodJournalStatus()
        refreshLocalRiskAndInsights()
        hasLoadedPersistedData = true
    }

    func loadPersistedDataIfNeeded(from context: ModelContext) {
        guard !hasLoadedPersistedData else { return }
        let profileDescriptor = FetchDescriptor<StoredUserProfile>(
            sortBy: [SortDescriptor(\.updatedAt, order: .reverse)]
        )
        let profile = try? context.fetch(profileDescriptor).first
        clearStoredDailyCheckIns(in: context)
        loadPersistedDataIfNeeded(profile: profile)
    }

    func saveProfile(in context: ModelContext) {
        let missingItems = profileMissingDataItems()
        let descriptor = FetchDescriptor<StoredUserProfile>(
            sortBy: [SortDescriptor(\.updatedAt, order: .reverse)]
        )
        if let existing = try? context.fetch(descriptor).first {
            existing.update(from: profile, missingItems: missingItems)
        } else {
            context.insert(StoredUserProfile(profile: profile, missingItems: missingItems))
        }
        try? context.save()
        refreshFeedbackIfReady()
        syncProfileToCloud()
    }

    func saveCheckIn(in context: ModelContext) {
        let missingItems = checkInMissingDataItems()
        let startOfToday = Calendar.current.startOfDay(for: Date())
        let descriptor = FetchDescriptor<StoredDailyCheckIn>(
            sortBy: [SortDescriptor(\.updatedAt, order: .reverse)]
        )
        let existing = (try? context.fetch(descriptor))?
            .first { Calendar.current.isDate($0.checkInDate, inSameDayAs: startOfToday) }
        if let existing {
            existing.update(from: checkIn, missingItems: missingItems)
        } else {
            context.insert(StoredDailyCheckIn(checkIn: checkIn, missingItems: missingItems))
        }
        try? context.save()
        refreshFeedbackIfReady()
    }

    func refreshLocalRiskAndInsights() {
        guard canGenerateDailyFeedback else {
            markFeedbackWaitingForRequiredAnswers()
            return
        }
        let result = LocalRiskEngine.evaluate(profile: profile, checkIn: checkIn)
        weeklyRisk = result.risk
        dailyInsights = result.insights
        dailyInsightsSource = "Local rules"
    }

    func refreshRemoteDailyInsightsIfPossible() {
        guard canGenerateDailyFeedback else {
            markFeedbackWaitingForRequiredAnswers()
            return
        }
        let currentCheckIn = checkIn
        Task {
            do {
                let response = try await dailyInsightsAPI.generate(checkIn: currentCheckIn)
                let mapped = response.insights.map(\.dailyInsight)
                guard !mapped.isEmpty else { return }
                dailyInsights = mapped
                dailyInsightsSource = response.source == "openai_rewrite" ? "OpenAI rewrite" : "Backend rules fallback"
            } catch {
                dailyInsightsSource = "Local rules fallback"
            }
        }
    }

    private func resetDailyCheckInForNewSession() {
        checkIn = MockData.checkIn
        checkInSource = "manual_entry"
        checkInProvenance = [:]
        nutritionEstimateMessage = ""
        isEstimatingNutrition = false
    }

    private func clearStoredDailyCheckIns(in context: ModelContext) {
        let descriptor = FetchDescriptor<StoredDailyCheckIn>()
        guard let savedCheckIns = try? context.fetch(descriptor) else { return }
        for savedCheckIn in savedCheckIns {
            context.delete(savedCheckIn)
        }
        try? context.save()
    }

    var currentModelInputPayload: ModelInputPayload {
        ModelInputMapper.makePayload(profile: profile, checkIn: checkIn)
    }

    func refreshRemoteRiskPredictionIfPossible() {
        guard canGenerateDailyFeedback else {
            markFeedbackWaitingForRequiredAnswers()
            return
        }
        let payload = currentModelInputPayload
        if !payload.missingRequiredInputs.isEmpty {
            riskPredictionMode = .unavailable("Complete required model inputs to use the trained prediction model.")
            syncCheckInToCloud()
            return
        }

        riskPredictionMode = .loadingRemote
        Task {
            do {
                let response = try await riskPredictionAPI.predict(payload: payload)
                applyRemoteRiskPrediction(response)
                syncCheckInToCloud(riskResult: response)
            } catch {
                riskPredictionMode = .unavailable(error.localizedDescription)
                syncCheckInToCloud()
            }
        }
    }

    private func refreshFeedbackIfReady() {
        guard canGenerateDailyFeedback else {
            markFeedbackWaitingForRequiredAnswers()
            return
        }
        refreshLocalRiskAndInsights()
        refreshRemoteDailyInsightsIfPossible()
        refreshRemoteRiskPredictionIfPossible()
    }

    private func markFeedbackWaitingForRequiredAnswers() {
        weeklyRisk = MockData.weeklyRiskNotReady
        dailyInsights = []
        dailyInsightsSource = "Waiting for required answers"
        riskPredictionMode = .unavailable("Complete all required profile and check-in answers to generate feedback.")
    }

    func estimateFoodNutrition(text: String? = nil, imageBase64: [String] = []) {
        let description = text ?? checkIn.foodJournalDescription
        let trimmedDescription = description.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedDescription.isEmpty || !imageBase64.isEmpty else {
            nutritionEstimateMessage = "Add a food description or photo first."
            return
        }

        isEstimatingNutrition = true
        nutritionEstimateMessage = "Estimating food nutrition..."
        Task {
            do {
                let result = try await nutritionEstimateAPI.estimate(
                    text: trimmedDescription,
                    imageBase64: imageBase64
                )
                applyNutritionEstimate(result)
            } catch {
                let fallback = LocalNutritionEstimator.estimate(
                    text: trimmedDescription,
                    imageCount: imageBase64.count
                )
                applyNutritionEstimate(fallback)
            }
            isEstimatingNutrition = false
        }
    }

    private func applyNutritionEstimate(_ result: NutritionEstimateResponse) {
        let hasNutrition = result.calories > 0 || result.carbohydrates > 0 || result.protein > 0 || result.fat > 0
        guard hasNutrition else {
            checkIn.foodCalories = ""
            checkIn.foodCarbohydrates = ""
            checkIn.foodProtein = ""
            checkIn.foodFat = ""
            checkIn.foodNutritionSource = result.source
            checkIn.foodNutritionConfidence = result.confidence
            checkIn.foodNutritionExplanation = result.explanation
            checkIn.foodNutritionMatchedFoods = result.matchedFoods.joined(separator: ", ")
            if !checkIn.foodJournalDescription.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || checkIn.foodPhotoCount > 0 {
                checkIn.foodJournal = "Added"
            }
            nutritionEstimateMessage = "Food note saved. Nutrition could not be estimated yet."
            refreshFeedbackIfReady()
            return
        }
        checkIn.foodCalories = "\(result.calories)"
        checkIn.foodCarbohydrates = Self.formatMacro(result.carbohydrates)
        checkIn.foodProtein = Self.formatMacro(result.protein)
        checkIn.foodFat = Self.formatMacro(result.fat)
        checkIn.foodNutritionSource = result.source
        checkIn.foodNutritionConfidence = result.confidence
        checkIn.foodNutritionExplanation = result.explanation
        checkIn.foodNutritionMatchedFoods = result.matchedFoods.joined(separator: ", ")
        checkIn.foodJournal = "Added"
        if result.source.contains("fallback") {
            nutritionEstimateMessage = "Low-confidence estimate: \(checkIn.foodJournalSummary)"
        } else if result.source.contains("local") {
            nutritionEstimateMessage = "On-device estimate: \(checkIn.foodJournalSummary)"
        } else {
            nutritionEstimateMessage = "AI estimate: \(checkIn.foodJournalSummary)"
        }
        refreshFeedbackIfReady()
    }

    private static func formatMacro(_ value: Double) -> String {
        if value.rounded() == value {
            return "\(Int(value))"
        }
        return String(format: "%.1f", value)
    }

    func logIn() {
        authenticate(isRegistering: false)
    }

    func createAccount() {
        authenticate(isRegistering: true)
    }

    func acceptPrivacyTerms() {
        hasAcceptedPrivacyTerms = true
        UserDefaults.standard.set(true, forKey: "hasAcceptedPrivacyTerms")
    }

    func signOut() {
        authToken = nil
        accountEmail = ""
        authPassword = ""
        authMessage = "Signed out."
        cloudSyncMessage = ""
        KeychainStore.delete(account: "authToken")
        UserDefaults.standard.removeObject(forKey: "accountEmail")
    }

    func deleteAccount() {
        guard let authToken else {
            signOut()
            return
        }
        cloudSyncMessage = "Deleting account..."
        Task {
            do {
                try await accountAPI.deleteAccount(token: authToken)
                signOut()
                cloudSyncMessage = "Account deleted."
                screen = .welcome
            } catch {
                cloudSyncMessage = "Account deletion failed: \(error.localizedDescription)"
            }
        }
    }

    func exportAccountData() {
        guard let authToken else {
            cloudSyncMessage = "Sign in to export cloud data."
            return
        }
        cloudSyncMessage = "Exporting account data..."
        Task {
            do {
                let data = try await accountAPI.exportAccountData(token: authToken)
                let kilobytes = max(1, data.count / 1024)
                cloudSyncMessage = "Data export ready (\(kilobytes) KB JSON)."
            } catch {
                cloudSyncMessage = "Data export failed: \(error.localizedDescription)"
            }
        }
    }

    private func normalizeFoodJournalStatus() {
        let hasDescription = !checkIn.foodJournalDescription.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        let hasPhotos = checkIn.foodPhotoCount > 0
        let hasNutrition = [
            checkIn.foodCalories,
            checkIn.foodCarbohydrates,
            checkIn.foodProtein,
            checkIn.foodFat,
        ].contains { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
        if checkIn.foodJournal == "Added" && !hasDescription && !hasPhotos && !hasNutrition {
            checkIn.foodJournal = ""
            checkIn.foodNutritionSource = ""
            checkIn.foodNutritionConfidence = ""
            checkIn.foodNutritionExplanation = ""
            checkIn.foodNutritionMatchedFoods = ""
        }
    }

    private func authenticate(isRegistering: Bool) {
        guard hasAcceptedPrivacyTerms else {
            authMessage = "Review and accept Privacy & Safety before continuing."
            return
        }
        guard !authEmail.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            authMessage = "Enter your email."
            return
        }
        guard authPassword.count >= 8 else {
            authMessage = "Password must be at least 8 characters."
            return
        }

        isAuthenticating = true
        authMessage = isRegistering ? "Creating account..." : "Signing in..."
        Task {
            do {
                let response: AuthResponse
                if isRegistering {
                    response = try await accountAPI.register(
                        email: authEmail,
                        password: authPassword,
                        name: profile.name
                    )
                } else {
                    response = try await accountAPI.login(
                        email: authEmail,
                        password: authPassword
                    )
                }

                authToken = response.token
                accountEmail = response.user.email
                KeychainStore.save(response.token, account: "authToken")
                UserDefaults.standard.set(response.user.email, forKey: "accountEmail")
                authMessage = isRegistering ? "Account created." : "Signed in."
                cloudSyncMessage = "Signed in as \(response.user.email)"
                isAuthenticating = false

                if isRegistering {
                    syncProfileToCloud()
                    screen = .profile
                } else {
                    await loadCloudData()
                    showMain(tab: .home)
                }
            } catch {
                isAuthenticating = false
                authMessage = "\(error.localizedDescription) Please try again once; the free demo server may still be waking up. For demo, you can tap Continue without account."
            }
        }
    }

    private func loadCloudData() async {
        guard let authToken else { return }
        isCloudSyncing = true
        do {
            if let cloudProfile = try await accountAPI.fetchProfile(token: authToken) {
                profile = cloudProfile
            }
            if let cloudCheckIn = try await accountAPI.fetchLatestCheckIn(token: authToken) {
                checkIn = cloudCheckIn
                normalizeFoodJournalStatus()
            }
            refreshFeedbackIfReady()
            cloudSyncMessage = "Cloud data loaded."
        } catch {
            cloudSyncMessage = "Could not load cloud data: \(error.localizedDescription)"
        }
        isCloudSyncing = false
    }

    private func syncProfileToCloud() {
        guard let authToken else { return }
        isCloudSyncing = true
        Task {
            do {
                try await accountAPI.saveProfile(profile, token: authToken)
                cloudSyncMessage = "Profile synced to cloud."
            } catch {
                cloudSyncMessage = "Profile sync failed: \(error.localizedDescription)"
            }
            isCloudSyncing = false
        }
    }

    private func syncCheckInToCloud(riskResult: RiskPredictionResponse? = nil) {
        guard let authToken else { return }
        let payload = currentModelInputPayload
        isCloudSyncing = true
        Task {
            do {
                try await accountAPI.saveCheckIn(
                    checkIn,
                    token: authToken,
                    modelPayload: payload,
                    riskResult: riskResult,
                    source: checkInSource,
                    provenance: checkInProvenance
                )
                cloudSyncMessage = "Check-in synced to cloud."
            } catch {
                cloudSyncMessage = "Check-in sync failed: \(error.localizedDescription)"
            }
            isCloudSyncing = false
        }
    }

    private func applyRemoteRiskPrediction(_ response: RiskPredictionResponse) {
        weeklyRisk = WeeklyRisk(
            score: response.percent,
            band: response.band,
            increasing: response.increasingFactors,
            decreasing: response.decreasingFactors
        )
        riskPredictionMode = .remoteModel
    }

    func profileMissingDataItems() -> [MissingDataItem] {
        var items: [MissingDataItem] = []
        addRequiredString(&items, field: "name", label: "Name", value: profile.name)
        addRequiredString(&items, field: "age", label: "Age", value: profile.age)
        addRequiredChoice(&items, field: "sex_at_birth", label: "Sex assigned at birth", value: profile.sexAtBirth)
        if profile.sexAtBirth == "Female" {
            addRequiredChoice(&items, field: "pregnancy_history", label: "Pregnancy history", value: profile.hasBeenPregnant)
            if profile.hasBeenPregnant == "Yes" {
                addRequiredChoice(&items, field: "gestational_diabetes", label: "Gestational diabetes history", value: profile.gestationalDiabetes)
            }
        }
        if profile.raceEthnicity.isEmpty {
            items.append(MissingDataItem(field: "race_ethnicity", label: "Race and ethnicity", code: MissingDataCode.missing))
        } else if profile.raceEthnicity.contains("Prefer not to answer") {
            items.append(MissingDataItem(field: "race_ethnicity", label: "Race and ethnicity", code: MissingDataCode.preferNotToAnswer))
        }
        addRequiredString(&items, field: "height_feet", label: "Height feet", value: profile.heightFeet)
        addRequiredString(&items, field: "height_inches", label: "Height inches", value: profile.heightInches)
        addRequiredChoice(&items, field: "family_history_diabetes", label: "Family history of diabetes", value: profile.familyHistoryDiabetes)
        addRequiredChoice(&items, field: "hypertension_history", label: "Hypertension history", value: profile.hypertensionHistory)
        addRequiredChoice(&items, field: "antihypertensive_medication", label: "Antihypertensive medication use", value: profile.antihypertensiveMedication)
        addRequiredChoice(&items, field: "high_cholesterol", label: "High cholesterol", value: profile.highCholesterol)
        addRequiredChoice(&items, field: "smoking_status", label: "Smoking status", value: profile.smokingStatus)
        addRequiredChoice(&items, field: "alcohol_frequency", label: "Alcohol frequency", value: profile.alcoholFrequency)
        return items
    }

    func checkInMissingDataItems() -> [MissingDataItem] {
        var items: [MissingDataItem] = []
        if shouldShowWeeklyCheckIn {
            addRequiredString(&items, field: "weight", label: "Weight", value: checkIn.weight)
            addRequiredString(&items, field: "waist_circumference", label: "Waist circumference", value: checkIn.waist)
            if checkIn.hasRecentBloodPressure {
                addRequiredString(&items, field: "systolic_bp", label: "Systolic blood pressure", value: checkIn.systolic)
                addRequiredString(&items, field: "diastolic_bp", label: "Diastolic blood pressure", value: checkIn.diastolic)
                addRequiredString(&items, field: "blood_pressure_date", label: "Blood pressure date measured", value: checkIn.bloodPressureDate)
            }
        }
        addRequiredString(&items, field: "sleep_hours", label: "Sleep duration", value: checkIn.sleepHours)
        if checkIn.activeToday == nil {
            items.append(MissingDataItem(field: "physical_activity_today", label: "Physical activity", code: MissingDataCode.missing))
        } else if checkIn.activeToday == true {
            addRequiredChoice(&items, field: "activity_type", label: "Activity type", value: checkIn.activityType)
            addRequiredString(&items, field: "activity_duration", label: "Activity duration", value: checkIn.activityDuration)
        }
        addRequiredChoice(&items, field: "movement_breaks", label: "Movement breaks", value: checkIn.movementBreaks)
        addRequiredString(&items, field: "daily_reflection", label: "Daily reflection", value: checkIn.dailyReflection)
        return items
    }

    private func addRequiredString(_ items: inout [MissingDataItem], field: String, label: String, value: String) {
        if value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            items.append(MissingDataItem(field: field, label: label, code: MissingDataCode.missing))
        }
    }

    private func addRequiredChoice(_ items: inout [MissingDataItem], field: String, label: String, value: String) {
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty {
            items.append(MissingDataItem(field: field, label: label, code: MissingDataCode.missing))
        } else if trimmed == "Prefer not to answer" {
            items.append(MissingDataItem(field: field, label: label, code: MissingDataCode.preferNotToAnswer))
        } else if trimmed == "Not sure" {
            items.append(MissingDataItem(field: field, label: label, code: MissingDataCode.notSure))
        }
    }

    func applyHealthImport(_ result: HealthImportResult) {
        var importedFields: [String] = []
        if let weightPounds = result.weightPounds {
            checkIn.weight = String(format: "%.0f", weightPounds)
            checkIn.weightUnit = "lb"
            importedFields.append("weight")
        }
        if let systolic = result.systolic, let diastolic = result.diastolic {
            checkIn.systolic = String(format: "%.0f", systolic)
            checkIn.diastolic = String(format: "%.0f", diastolic)
            checkIn.bloodPressureDate = result.bloodPressureDate.map(Self.healthImportDateFormatter.string(from:)) ?? "Apple Health"
            checkIn.hasRecentBloodPressure = true
            importedFields.append("blood_pressure")
        }
        if let sleepHours = result.sleepHours {
            checkIn.sleepHours = String(format: "%.1f", sleepHours)
            importedFields.append("sleep_hours")
        }
        if let activityMinutes = result.activityMinutes, activityMinutes > 0 {
            checkIn.activeToday = true
            checkIn.activityType = result.activityName ?? "Workout"
            checkIn.activityDuration = "\(activityMinutes)"
            importedFields.append("physical_activity")
        }
        if !importedFields.isEmpty {
            checkInSource = "apple_health_confirmed"
            checkInProvenance = [
                "source": "apple_health",
                "confirmation": "user_confirmed",
                "confirmed_at": Self.isoDateFormatter.string(from: Date()),
                "imported_fields": importedFields.joined(separator: ","),
                "sleep_window": "last_night",
                "activity_window": "today",
                "body_metrics_window": "latest_30_days",
            ]
            if let weightDate = result.weightDate {
                checkInProvenance["weight_measured_at"] = Self.isoDateFormatter.string(from: weightDate)
            }
            if let bloodPressureDate = result.bloodPressureDate {
                checkInProvenance["blood_pressure_measured_at"] = Self.isoDateFormatter.string(from: bloodPressureDate)
            }
        }
        refreshFeedbackIfReady()
    }

    private static let healthImportDateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "MMM d"
        return formatter
    }()

    private static let isoDateFormatter = ISO8601DateFormatter()

    private func iconName(for domain: String) -> String {
        switch domain {
        case "sleep":
            return "moon.zzz"
        case "movement":
            return "figure.stand"
        case "diet":
            return "fork.knife"
        case "alcohol":
            return "wineglass"
        case "maintenance":
            return "checkmark.circle"
        default:
            return "sparkles"
        }
    }

    private static func isWeeklyCheckInDay(_ date: Date, weekday: Int) -> Bool {
        Calendar.current.component(.weekday, from: date) == weekday
    }
}

struct UserProfile: Codable {
    var name: String
    var age: String
    var sexAtBirth: String
    var hasBeenPregnant: String
    var gestationalDiabetes: String
    var raceEthnicity: [String]
    var heightFeet: String
    var heightInches: String
    var familyHistoryDiabetes: String
    var hypertensionHistory: String
    var antihypertensiveMedication: String
    var highCholesterol: String
    var smokingStatus: String
    var alcoholFrequency: String

    var featureFlags: [String: Int] {
        [
            "name": answeredFeatureFlag(name),
            "age": answeredFeatureFlag(age),
            "sex_at_birth": answeredFeatureFlag(sexAtBirth),
            "pregnancy_history": answeredFeatureFlag(hasBeenPregnant),
            "gestational_diabetes": answeredFeatureFlag(gestationalDiabetes),
            "race_ethnicity": raceEthnicity.isEmpty ? 0 : 1,
            "height_feet": answeredFeatureFlag(heightFeet),
            "height_inches": answeredFeatureFlag(heightInches),
            "family_history_diabetes": answeredFeatureFlag(familyHistoryDiabetes),
            "hypertension_history": answeredFeatureFlag(hypertensionHistory),
            "antihypertensive_medication": answeredFeatureFlag(antihypertensiveMedication),
            "high_cholesterol": answeredFeatureFlag(highCholesterol),
            "smoking_status": answeredFeatureFlag(smokingStatus),
            "alcohol_frequency": answeredFeatureFlag(alcoholFrequency),
        ]
    }
}

struct DailyCheckIn: Codable {
    var weight: String
    var weightUnit: String
    var waist: String
    var waistUnit: String
    var systolic: String
    var diastolic: String
    var bloodPressureDate: String
    var hasRecentBloodPressure: Bool
    var sleepHours: String
    var activeToday: Bool?
    var activityType: String
    var activityDuration: String
    var movementBreaks: String
    var foodJournal: String
    var foodJournalDescription: String
    var foodPhotoCount: Int
    var foodCalories: String
    var foodCarbohydrates: String
    var foodProtein: String
    var foodFat: String
    var foodNutritionSource: String
    var foodNutritionConfidence: String
    var foodNutritionExplanation: String
    var foodNutritionMatchedFoods: String
    var dailyReflection: String
    var isCompleted: Bool

    var featureFlags: [String: Int] {
        [
            "weight": answeredFeatureFlag(weight),
            "waist_circumference": answeredFeatureFlag(waist),
            "blood_pressure": hasRecentBloodPressure && answeredFeatureFlag(systolic) == 1 && answeredFeatureFlag(diastolic) == 1 ? 1 : 0,
            "blood_pressure_date": answeredFeatureFlag(bloodPressureDate),
            "sleep_hours": answeredFeatureFlag(sleepHours),
            "physical_activity_today": activeToday == nil ? 0 : 1,
            "activity_type": answeredFeatureFlag(activityType),
            "activity_duration": answeredFeatureFlag(activityDuration),
            "movement_breaks": answeredFeatureFlag(movementBreaks),
            "food_journal": answeredFeatureFlag(foodJournal),
            "food_journal_description": answeredFeatureFlag(foodJournalDescription),
            "food_photo": foodPhotoCount > 0 ? 1 : 0,
            "food_nutrition": [foodCalories, foodCarbohydrates, foodProtein, foodFat].contains { answeredFeatureFlag($0) == 1 } ? 1 : 0,
            "daily_reflection": answeredFeatureFlag(dailyReflection),
        ]
    }

    var foodJournalSummary: String {
        if foodJournal == "Skipped" {
            return "Skipped"
        }

        var parts: [String] = []
        let calories = foodCalories.trimmingCharacters(in: .whitespacesAndNewlines)
        let carbs = foodCarbohydrates.trimmingCharacters(in: .whitespacesAndNewlines)
        let protein = foodProtein.trimmingCharacters(in: .whitespacesAndNewlines)
        let fat = foodFat.trimmingCharacters(in: .whitespacesAndNewlines)

        if !calories.isEmpty {
            parts.append("\(calories) kcal")
        }
        if !carbs.isEmpty {
            parts.append("C \(carbs)g")
        }
        if !protein.isEmpty {
            parts.append("P \(protein)g")
        }
        if !fat.isEmpty {
            parts.append("F \(fat)g")
        }
        if !parts.isEmpty {
            return parts.joined(separator: " · ")
        }
        if foodPhotoCount > 0 {
            return "\(foodPhotoCount) photo\(foodPhotoCount == 1 ? "" : "s")"
        }
        if !foodJournalDescription.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return "Notes added"
        }
        return "Not added"
    }

    enum CodingKeys: String, CodingKey {
        case weight
        case weightUnit
        case waist
        case waistUnit
        case systolic
        case diastolic
        case bloodPressureDate
        case hasRecentBloodPressure
        case sleepHours
        case activeToday
        case activityType
        case activityDuration
        case movementBreaks
        case foodJournal
        case foodJournalDescription
        case foodPhotoCount
        case foodCalories
        case foodCarbohydrates
        case foodProtein
        case foodFat
        case foodNutritionSource
        case foodNutritionConfidence
        case foodNutritionExplanation
        case foodNutritionMatchedFoods
        case dailyReflection
        case isCompleted
    }

    init(
        weight: String,
        weightUnit: String,
        waist: String,
        waistUnit: String,
        systolic: String,
        diastolic: String,
        bloodPressureDate: String,
        hasRecentBloodPressure: Bool,
        sleepHours: String,
        activeToday: Bool?,
        activityType: String,
        activityDuration: String,
        movementBreaks: String,
        foodJournal: String,
        foodJournalDescription: String = "",
        foodPhotoCount: Int = 0,
        foodCalories: String = "",
        foodCarbohydrates: String = "",
        foodProtein: String = "",
        foodFat: String = "",
        foodNutritionSource: String = "",
        foodNutritionConfidence: String = "",
        foodNutritionExplanation: String = "",
        foodNutritionMatchedFoods: String = "",
        dailyReflection: String,
        isCompleted: Bool
    ) {
        self.weight = weight
        self.weightUnit = weightUnit
        self.waist = waist
        self.waistUnit = waistUnit
        self.systolic = systolic
        self.diastolic = diastolic
        self.bloodPressureDate = bloodPressureDate
        self.hasRecentBloodPressure = hasRecentBloodPressure
        self.sleepHours = sleepHours
        self.activeToday = activeToday
        self.activityType = activityType
        self.activityDuration = activityDuration
        self.movementBreaks = movementBreaks
        self.foodJournal = foodJournal
        self.foodJournalDescription = foodJournalDescription
        self.foodPhotoCount = foodPhotoCount
        self.foodCalories = foodCalories
        self.foodCarbohydrates = foodCarbohydrates
        self.foodProtein = foodProtein
        self.foodFat = foodFat
        self.foodNutritionSource = foodNutritionSource
        self.foodNutritionConfidence = foodNutritionConfidence
        self.foodNutritionExplanation = foodNutritionExplanation
        self.foodNutritionMatchedFoods = foodNutritionMatchedFoods
        self.dailyReflection = dailyReflection
        self.isCompleted = isCompleted
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        weight = try container.decode(String.self, forKey: .weight)
        weightUnit = try container.decode(String.self, forKey: .weightUnit)
        waist = try container.decode(String.self, forKey: .waist)
        waistUnit = try container.decode(String.self, forKey: .waistUnit)
        systolic = try container.decode(String.self, forKey: .systolic)
        diastolic = try container.decode(String.self, forKey: .diastolic)
        bloodPressureDate = try container.decode(String.self, forKey: .bloodPressureDate)
        hasRecentBloodPressure = try container.decode(Bool.self, forKey: .hasRecentBloodPressure)
        sleepHours = try container.decode(String.self, forKey: .sleepHours)
        activeToday = try container.decodeIfPresent(Bool.self, forKey: .activeToday)
        activityType = try container.decode(String.self, forKey: .activityType)
        activityDuration = try container.decode(String.self, forKey: .activityDuration)
        movementBreaks = try container.decode(String.self, forKey: .movementBreaks)
        foodJournal = try container.decode(String.self, forKey: .foodJournal)
        foodJournalDescription = try container.decodeIfPresent(String.self, forKey: .foodJournalDescription) ?? ""
        foodPhotoCount = try container.decodeIfPresent(Int.self, forKey: .foodPhotoCount) ?? 0
        foodCalories = try container.decodeIfPresent(String.self, forKey: .foodCalories) ?? ""
        foodCarbohydrates = try container.decodeIfPresent(String.self, forKey: .foodCarbohydrates) ?? ""
        foodProtein = try container.decodeIfPresent(String.self, forKey: .foodProtein) ?? ""
        foodFat = try container.decodeIfPresent(String.self, forKey: .foodFat) ?? ""
        foodNutritionSource = try container.decodeIfPresent(String.self, forKey: .foodNutritionSource) ?? ""
        foodNutritionConfidence = try container.decodeIfPresent(String.self, forKey: .foodNutritionConfidence) ?? ""
        foodNutritionExplanation = try container.decodeIfPresent(String.self, forKey: .foodNutritionExplanation) ?? ""
        foodNutritionMatchedFoods = try container.decodeIfPresent(String.self, forKey: .foodNutritionMatchedFoods) ?? ""
        dailyReflection = try container.decode(String.self, forKey: .dailyReflection)
        isCompleted = try container.decode(Bool.self, forKey: .isCompleted)
    }
}

private func answeredFeatureFlag(_ value: String) -> Int {
    value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? 0 : 1
}

struct WeeklyRisk: Codable {
    var score: Int
    var band: String
    var increasing: [String]
    var decreasing: [String]
}

enum MockData {
    static let profile = UserProfile(
        name: "",
        age: "",
        sexAtBirth: "",
        hasBeenPregnant: "",
        gestationalDiabetes: "",
        raceEthnicity: [],
        heightFeet: "",
        heightInches: "",
        familyHistoryDiabetes: "",
        hypertensionHistory: "",
        antihypertensiveMedication: "",
        highCholesterol: "",
        smokingStatus: "",
        alcoholFrequency: ""
    )

    static let checkIn = DailyCheckIn(
        weight: "",
        weightUnit: "lb",
        waist: "",
        waistUnit: "in",
        systolic: "",
        diastolic: "",
        bloodPressureDate: "",
        hasRecentBloodPressure: false,
        sleepHours: "",
        activeToday: nil,
        activityType: "",
        activityDuration: "",
        movementBreaks: "",
        foodJournal: "",
        foodJournalDescription: "",
        foodPhotoCount: 0,
        foodCalories: "",
        foodCarbohydrates: "",
        foodProtein: "",
        foodFat: "",
        foodNutritionSource: "",
        foodNutritionConfidence: "",
        foodNutritionExplanation: "",
        foodNutritionMatchedFoods: "",
        dailyReflection: "",
        isCompleted: false
    )

    static let weeklyRiskNotReady = WeeklyRisk(
        score: 0,
        band: "Not Ready",
        increasing: [],
        decreasing: []
    )

    static let weeklyRisk = weeklyRiskNotReady

    static let dailyInsights: [DailyInsight] = []
}
